### PR TITLE
Scene importer

### LINKED ISSUE #920: ACE requires stropts.h which is omitted on some Linux desktops
### Describe the bug
When building the project ACE requires stropts.h which is omitted on some Linux desktops, such as Fedora-based distros, see: https://bugzilla.redhat.com/show_bug.cgi?id=656245

### Resolution
This omission is deliberate in these distros (per the link above), but there may be a workaround. Researching now.

### PR DESCRIPTION
**Pull request by nemerle**
SegsEngine sdk integration + various updates
WIP coh loaders/importers for the engine

### CODE REVIEW

File: Components/serialization_common.h [hunk 1]
```diff
@@ -60,18 +80,20 @@ void commonSaveTo(const T & target, const char *classname, const QString & baseN
 }
 
 template<class T>
-bool commonReadFrom(const QString &crl_path,const char *classname, T &target)
+bool commonReadFrom(FSWrapper &fs,const QString &crl_path,const char *classname, T &target)
```
Comment (broxen) [inline Components/serialization_common.h:83]: Why FSWrapper here instead of QFSWrapper

File: Projects/CoX/Common/GameData/scenegraph_serializers.cpp [hunk 2]
```diff
@@ -369,55 +371,52 @@ void saveTo(const SceneGraph_Data &target, const QString &baseName, bool text_fo
     commonSaveTo(target,"SceneGraph",baseName,text_format);
 }
 
-bool loadFrom(const QString &filepath, SceneGraph_Data &target)
+bool loadFrom(FSWrapper &fs, const QString &filepath, SceneGraph_Data &target)
```
Comment (broxen) [inline Projects/CoX/Common/GameData/scenegraph_serializers.cpp:374]: Again why FSWrapper vs QFSWrapper here?
