### PR TITLE
Stop excessive blank lines in SEGSAdmin output

### LINKED ISSUE #761: Excessive line feeds in server output
### Describe the bug:
Excessive line feeds in server output.

### To Reproduce:
Start SEGSAdmin, start server, observe logins and actions.

### Expected behavior:
Line feeds that make sense, if any.

### SEGS Version:
 - SEGS Build ID: 0.6.1

### PR DESCRIPTION
**Pull request by miles200**
Change use of function from appendPlainText() to insertPlainText()

### Issues closed
Closes #761

### CODE REVIEW

File: Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp [hunk 1]
```diff
@@ -379,8 +381,9 @@ void SEGSAdminTool::read_segsserver()
     QString output_std = out_std;
     output_err.replace("Press ENTER to continue...", "** FINISHED **");
     output_std.replace("Press ENTER to continue...", "** FINISHED **");
-    ui->output->appendPlainText(output_err);
-    ui->output->appendPlainText(output_std);
+    ui->output->insertPlainText(output_err);
+    ui->output->insertPlainText(output_std);
+    ui->output->moveCursor(QTextCursor::End);
```
Comment (dracc) [inline Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp]: nit: Swapped order?

**Comment by miles200** [comment]
Okay this is ready for merge if build passes and reviewers happy, cheers

**Comment by broxen** [comment]
Will squash and merge once CI clears
