### PR TITLE
Fly on jump fix

### LINKED ISSUE #241: Make client side movement more bearable : set the fly bit on jump
When we jump now, the server simply increments the current Y coordinate of the player.

Since the server-side position never 'falls' with gravity, and client firmly believes that what comes up must go down, we could at least prevent 'forever falling' thing, by setting a proper bit in the entity, thus marking it as a flying one.

**Required skills**: c++
**Required knowledge**: ability to find the proper bit in Entity and set it when first 'jump' event arrives for that entity.

Thanks go to: @mobbyg for inspiration 💡

### PR DESCRIPTION
**Pull request by miles200**
Closes #241  .

Additions/modifications proposed in this pull request:
- Added a function to set m_is_flying within Entity to true on jump event
- 
-

### CODE REVIEW

File: Projects/CoX/Servers/MapServer/WorldSimulation.cpp [hunk 1]
```diff
@@ -3,9 +3,16 @@
 #include "MapClient.h"
 #include "AdminServer.h"
 #include "Database.h"
+#include "Events/InputState.cpp"
```
Comment (nemerle) [inline Projects/CoX/Servers/MapServer/WorldSimulation.cpp]: Ha, in c++ we include `.h` files my friend
Unless we do something funky :wink:

File: Projects/CoX/Servers/MapServer/WorldSimulation.cpp [hunk 2]
```diff
@@ -37,8 +43,17 @@ void World::physicsStep(Entity *e,uint32_t msec)
         float vel_scale = e->inp_state.input_vel_scale/255.0f;
         e->m_entity_data.m_pos += ((za*e->inp_state.pos_delta)*float(msec))/50.0f;
         e->vel = za*e->inp_state.pos_delta;
+
     }
+
+    if(e->inp_state.pos_delta[1] == float(1.0f)) // Will set 'is flying' on jump event
+
```
Comment (nemerle) [inline Projects/CoX/Servers/MapServer/WorldSimulation.cpp]: Hmm.. I'm seeing double new-lines here as well as in markFlying ? Single new line is ok here:
```cpp
{
  something();
}```

Comment (miles200) [reply Projects/CoX/Servers/MapServer/WorldSimulation.cpp]: Thanks fixed
