### PR TITLE
SEGSAdmin fix for BinConverter on Linux/MacOS

### LINKED ISSUE #921: BinConverter Error: execvp: No such file or directory
### Describe the bug
BinConverter Appears to fail on something called `execvp`. Not sure why SEGAdmin is spitting out `execvp`. May relate to changes in #918 

### To Reproduce
1. Compile in clean directory
2. Run SEGSAdmin, Setup Config and DBs
3. Select `Setup COH Data Files`
4. See error: `BinConverter Error: execvp: No such file or directory`

### PR DESCRIPTION
**Pull request by miles200**
## Summary
Made some changes to the path used when running BinConverter within SEGSAdmin to fix Linux not finding the executable and subsequently the data/ent_types directory

### Issues closed
Closes #921

### CODE REVIEW

File: Projects/CoX/Utilities/SEGSAdmin/Worker.cpp [hunk 1]
```diff
@@ -69,7 +69,8 @@ bool Worker::processPiggFile(const QString &file)
 bool Worker::runBinConverter()
 {
     emit sendUIMessage("Starting BinConverter");
-    QString program = "utilities/binconverter data/ent_types";
+    //QString program = "utilities/binconverter data/ent_types";
```
Comment (miles200) [inline Projects/CoX/Utilities/SEGSAdmin/Worker.cpp]: Woops, let me fix this

**Review by broxen — APPROVED** [review]
