### PR TITLE
SEGSAdmin tool - fix for Fedora (and possibly other Linux distros)

### LINKED ISSUE #391: New SEGSAdmin app cannot execute dbtool or authserver on Linux
### Steps to reproduce
- Open SEGSAdmin
- Click on *CreateDatabases* button ... fails to open dbtool
- Click on *Add User Account* button ... fails to open dbtool
- Click on *Start Auth Server* button ... fails to open authserver

### Proposed solution
Not sure. Perhaps it's a linux filepath issue? Or permissions issue? Will need to test further.

### SEGS version and Build Info
Segs commit 17c664b
Qt 5.9.4 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 7.3.1 20180130 (Red Hat 7.3.1-2)) on "xcb"
OS: Fedora 27 (Workstation Edition) [linux version 4.16.5-200.fc27.x86_64]
Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2

### PR DESCRIPTION
**Pull request by miles200**
Closes #391  .

Restructured QProcess program/arguments to remove specific pointer to 'cmd.exe.' / 'xterm' etc, fixes issue on Fedora where xterm not installed by default

### CODE REVIEW

File: Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp [hunk 1]
```diff
@@ -156,37 +141,20 @@ void SEGSAdminTool::create_databases(bool overwrite)
     ui->output->appendPlainText("Setting arguments...");
     qApp->processEvents();
     qDebug() << "Setting arguments...";
-    QString dbcommand = "dbtool create";
+    QString program = "dbtool create";
     if (overwrite)
     {
-        dbcommand = dbcommand + " -f";
+        program = program + " -f";
```
Comment (nemerle) [inline Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp]: this could be `program += " -f";

Comment (miles200) [reply Projects/CoX/Utilities/SEGSAdmin/SEGSAdminTool.cpp]: Thanks @nemerle changed
