### PR TITLE
[WIP] ACE dll build fix & SEGSAdmin BinConverter Addition

### LINKED ISSUE #901: Failed to open "./data/converted/ent_types.crl.json"
## Summary
Server cannot find `./data/converted/ent_types.crl.json`, which presumably is created during pigg extraction. While some code to create `ent_types.crl.json` exists in binconverter, I'm unable to produce the file on a clean install with SEGSAdmin, or by running binconverter manually.

### PR DESCRIPTION
**Pull request by miles200**
## Summary
When building with MSVC, segs_server failed to start due to missing ACE.dll in the builds 'out' directory. `3rd_party/CMakeLists.txt` was not moving the dll due to the copy being inside the if clause `if(MINGW)` and the compiler used being MSVC. 

Added SEGSAdmin BinConverter process to data setup.

### Issues closed
Closes #901

### Additions/modifications proposed in this pull request:
- Included MSVC in command to copy dll within `3rd_party/CMakeLists.txt`
- Removed debug postfix from ACE source CMakeLists for MSVC 
- Removed reference to debug location for MSVC within `ExternalProject_ACE.cmake`
- Code refactor within SetUpData.cpp. Wasn't happy with the event loop being used so moved to utilise QThread / Worker design for processing piggfiles. Other tidy up's within this class. 
- misc.pigg was missing from pigg file extraction, now added.
- BinConverter now runs at the end of pigg tool extraction to solve the issue reported on #901 
- Added further checks to ensure updated sub directories within 'data' exist (including 'converted')

### CODE REVIEW

File: Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp [hunk 1]
```diff
@@ -157,124 +203,75 @@ void SetUpData::copy_piggs_files()
...
-        counter++;
-        //Delete pigg file once done with it
-        QFile::remove(fileInfo.absoluteFilePath());
-    }
-    ui->progressBar_piggtool->setValue(100);
-    ui->icon_extract_pigg->show();
-    ui->piggtool_output->appendPlainText("Files Extracted");
-    emit getMapsDir();
-}
+//void SetUpData::pigg_dispatcher_wait_dialog()
```
Comment (broxen) [inline Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp:212]: Can we add a TODO comment here to make it clear that we need to come back to this unfinished code block

File: Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp [hunk 2]
```diff
@@ -157,124 +203,75 @@ void SetUpData::copy_piggs_files()
...
+//    case QMessageBox::No:
+//        emit quitPiggLoop();
+//        break;
+//    default:
+//        break;
+//    }
+//}
 
-void SetUpData::pigg_dispatcher_wait_dialog()
+// change to get maps_dir from settings.cfg
```
Comment (broxen) [inline Projects/CoX/Utilities/SEGSAdmin/SetUpData.cpp:232]: Appears as though you do this already below with `getMapsDir()` so this comment can be removed

**Review by broxen — COMMENTED** [review]
I haven't compiled and tested this yet, but I didn't see any reason why it shouldn't work as intended.

Just a couple of notes to provide clarity with comments.

I'll try to pull down and test Monday. Thanks Miles!

File: Projects/CoX/Utilities/SEGSAdmin/SetUpData.h [hunk 3]
```diff
@@ -25,29 +26,30 @@ class SetUpData : public QDialog
...
-    void pigg_tool_worker(QString program);
-    void create_default_directory(QString maps_dir);
-    void read_piggtool();
-    void pigg_dispatcher_wait_dialog();
-    void check_client_version();
+    bool copyPiggFiles();
+    bool createDefaultDirectorys();
+    bool checkClientVersion();
+    void extractPiggs();
+    void logUIMessage(QString message);
```
Comment (broxen) [inline Projects/CoX/Utilities/SEGSAdmin/SetUpData.h:38]: Just noticing this should probably be a const reference.
