### PR TITLE
addUser RPC Service and RPCTestClient

### LINKED ISSUE #435: Unable to create users while service is running
I am running current master branch build and when I go to add users it tells me the table is locked. This will be an issue when attempting to run production (Public) environments.

Repro steps:
Start authserver
run dbtool adduser -l username -p password

Response:
Table is locked failed to add user (Paraphrasing)

### LINKED ISSUE #772: AdminRPC Test Client
## Feature Summary
As we now have an AdminRPC framework in place and I'm assuming more methods will added over time, would an AdminRPC test client be helpful to anyone? Especially the webUI team? 

### Proposed Implementation
Simple application which takes server IP, AdminRPC method name and input parameters, calls service and returns result. 

Can be used to see what data is being returned, test an RPC method, without having to build it into something like SEGSAdmin

Open for discussion, may not be helpful for anyone :)

### PR DESCRIPTION
**Pull request by miles200**
## Summary
- Add a simple RPCTestClient to enable a quicker / easier way to test our RPC services. This is an optional build parameter in CMake. BUILD_RPC_TEST_CLIENT will need to be set to ON
- Add a new RPC service named addUser which will allow adding of users whilst segs_server is running and DB is locked.

### Issues closed
Closes #772 
Closes #435

### CODE REVIEW

File: Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp [hunk 1]
```diff
@@ -69,8 +69,12 @@ void AuthDBSyncHandler::on_create_account(CreateAccountMessage *msg)
     AuthDbSyncContext &db_ctx(m_db_context.localData());
     if(!db_ctx.addAccount(msg->m_data))
     {
-        msg->src()->putq(new AuthDbErrorMessage({db_ctx.getLastError()->text()},msg->session_token()));
+        if(msg->src() != nullptr)
+            msg->src()->putq(new AuthDbErrorMessage({db_ctx.getLastError()->text()},msg->session_token()));
     }
+    else
+        if(msg->src() != nullptr)
+            msg->src()->putq(new AuthDbErrorMessage({"OK"},msg->session_token()));
```
Comment (nemerle) [inline Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp]: Please rename AuthDbErrorMessage class to AuthDbStatusMessage, since we are now sending it even in a case when things went well.
Also, we might want to send an empty string instead of "OK". Checking for success can be done with a simple `isEmpty` call instead of string comparison.

File: Projects/CoX/Servers/AuthServer/AdminRPC.cpp [hunk 2]
```diff
@@ -67,44 +93,138 @@ bool AdminRPC::ReadConfig()
...
+/*!
+ * @brief       Add a user
+ * @param[in]   username
+ * @param[in]   password
+ * @param[in]   access_level
+ * @return      Returns a string, if successful "OK" otherwise an error
+ */
+
+QString AdminRPC::addUser(const QString &username, const QString &password, const int access_level)
+{
```
Comment (nemerle) [inline Projects/CoX/Servers/AuthServer/AdminRPC.cpp]: Since access_level is passed by value, there is no need to add `const` qualifier to it.

File: Projects/CoX/Servers/AuthServer/AdminRPC.cpp [hunk 3]
```diff
@@ -67,44 +93,138 @@ bool AdminRPC::ReadConfig()
...
+
+    // Create and insert a record of this request into m_completion_state
+    m_completion_state.insert(token, "");
+
+    qCDebug(logRPC) << "addUser call in progress";
+
+    EventProcessor *tgt = HandlerLocator::getAuthDB_Handler();
+    tgt->putq(new CreateAccountMessage({username, password, access_level}, fake_session_token, this));
+
+    QTimer *response_timer = new QTimer(this);
```
Comment (nemerle) [inline Projects/CoX/Servers/AuthServer/AdminRPC.cpp]: I think both of those timers could be constructed on the stack:
```cpp
QTimer response_timer(this);
QTimer timer(this);
```
this way we won't leak memory.

**Comment by dracc** [comment]
Apart from the things pointed out by @nemerle , this looks good to me. :+1:

File: Projects/CoX/Servers/AuthServer/AdminRPC.cpp [hunk 4]
```diff
@@ -67,44 +93,138 @@ bool AdminRPC::ReadConfig()
     return true;
 }
 
+/*!
+ * @brief Test method - heyServer
+ * @return Returns a bool, always true
+ */
+
```
Comment (broxen) [inline Projects/CoX/Servers/AuthServer/AdminRPC.cpp]: Thank you for adding these doxy comments, but please remove the extra line break after each comment.

File: Projects/CoX/Utilities/RPCTestClient/RPCTestClient.h [hunk 5]
```diff
@@ -0,0 +1,36 @@
+/*
+ * SEGS - Super Entity Game Server
+ * http://www.segs.io/
+ * Copyright (c) 2006 - 2019 SEGS Team (see AUTHORS.md)
+ * This software is licensed under the terms of the 3-clause BSD License. See LICENSE.md for details.
+ */
+
+#ifndef RPCTESTCLIENT_H
```
Comment (broxen) [inline Projects/CoX/Utilities/RPCTestClient/RPCTestClient.h]: For code consistency, let's use `#pragma once` here instead of include guards.

File: Projects/CoX/Servers/AuthServer/AdminRPC.h [hunk 6]
```diff
@@ -11,38 +11,68 @@
...
     Q_OBJECT
     class AuthHandler *m_auth_handler;
     friend void startRPCServer();
+
 private:
     AdminRPC(); // restrict construction to startRPCServer
-    ~AdminRPC();
+    ~AdminRPC() override;
+
+
```
Comment (broxen) [inline Projects/CoX/Servers/AuthServer/AdminRPC.h]: Please remove the excess line breaks in this class definition.

File: Projects/CoX/Servers/AuthServer/AdminRPC.h [hunk 7]
```diff
@@ -11,38 +11,68 @@
 #include <ace/INET_Addr.h>
 #include <ace/Synch.h>
 
+#include "Servers/HandlerLocator.h"
```
Comment (broxen) [inline Projects/CoX/Servers/AuthServer/AdminRPC.h]: Please order headers in the following order:
```cpp
#include "local.h"
#include <third/party/headers>
#include <std_library>
```
This helps with debugging, as described in detail here: https://blog.knatten.org/2010/07/01/the-order-of-include-directives-matter/

Comment (miles200) [reply Projects/CoX/Servers/AuthServer/AdminRPC.h]: Fixed pending push

File: Projects/CoX/Servers/AuthServer/AdminRPC.h (hunk 6 above)
Comment (miles200) [reply Projects/CoX/Servers/AuthServer/AdminRPC.h]: Fixed pending push

File: Projects/CoX/Utilities/RPCTestClient/RPCTestClient.h (hunk 5 above)
Comment (miles200) [reply Projects/CoX/Utilities/RPCTestClient/RPCTestClient.h]: Fixed pending push

File: Projects/CoX/Servers/AuthServer/AdminRPC.cpp (hunk 4 above)
Comment (miles200) [reply Projects/CoX/Servers/AuthServer/AdminRPC.cpp]: Fixed pending push

File: Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp [hunk 8]
```diff
@@ -69,8 +69,12 @@ void AuthDBSyncHandler::on_create_account(CreateAccountMessage *msg)
     AuthDbSyncContext &db_ctx(m_db_context.localData());
     if(!db_ctx.addAccount(msg->m_data))
     {
-        msg->src()->putq(new AuthDbErrorMessage({db_ctx.getLastError()->text()},msg->session_token()));
+        if(msg->src() != nullptr)
+            msg->src()->putq(new AuthDbErrorMessage({db_ctx.getLastError()->text()},msg->session_token()));
     }
+    else
```
[the remark this answers is not in the document]
Comment (miles200) [reply Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp]: Fixed pending push

File: Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp (hunk 1 above)
Comment (miles200) [reply Projects/CoX/Servers/AuthDatabase/AuthDBSyncHandler.cpp]: Fixed pending push

**Comment by miles200** [comment]
@broxen @nemerle all changes should be made, could you give it a once over please? Had a merge conflict with @dracc changes to AdminRPC but should be resolved

**Comment by miles200** [comment]
@broxen @nemerle 

Sorry before you merge, just noticed something has gone wrong in my conflict fixing / merging ... I have a file called compile_commands.json with 51,000+ code insertions... This isn't me, so not sure where it's come from. 

Any ideas??

**Comment by broxen** [comment]
Looks like something spit out by QTCreator or Clang as it has build information.

I'd simply add it to the `.ignore` file.

**Comment by miles200** [comment]
Okay sorry worked it out, was a compilation database I generated in error from Qt. I've just deleted it.

Should be good for merge if you are happy with review and builds pass.

Cheers

**Comment by broxen** [comment]
Thanks @miles200! Once you've had a chance to merge conflicts, I'll get this in.

**Comment by miles200** [comment]
@broxen Must have just conflicted with the merge of the other PR :smile: Should be sorted.

**Comment by broxen** [comment]
Once CI clears I'll merge.
