### PR TITLE
Fix erroneous inspiration counts and fixed messages when adding…

### LINKED ISSUE #577: countForLevel() is broken when level exceeds the value of schedule[i]
### Summary
countForLevel() fails to return the correct value when lvl is greater than the value of all members of schedule array.

### PR DESCRIPTION
**Pull request by broxen**
Fix erroneous inspiration counts and fixed messages when adding inspirations and enhancements using slash commands

Closes #577 and the 1x4 starting insp array issue identified in Discord
Relates to #545 

Additions/modifications proposed in this pull request:
- Modified countForLevel() to ensure it sends values when lvl is higher than pischedule value
- Modified `/addinsp` and `/addboost` to check for full insp or enhancement trays before sending messages to client
- Modified finalizeLevel() to utilize level instead of combat_level

### CODE REVIEW

File: Projects/CoX/Servers/MapServer/SlashCommand.cpp [hunk 1]
```diff
@@ -868,15 +868,23 @@ void cmdHandler_AddInspiration(const QString &cmd, MapClientSession &sess)
     CharacterData &cd = sess.m_ent->m_char->m_char_data;
     int space = cmd.indexOf(' ');
     QString val = cmd.mid(space+1);
-    QString floating_msg = FloatingInfoMsg.find(FloatingMsg_FoundInspiration).value();
-    QString msg = "Awarding Inspiration '" + val + "' to " + sess.m_ent->name();
+    QString msg = "There was an error adding this inspiration!";
```
Comment (dracc) [inline Projects/CoX/Servers/MapServer/SlashCommand.cpp]: nit: Does `msg` need an initialization here, as it's always changed anyways?

File: Projects/CoX/Servers/MapServer/SlashCommand.cpp [hunk 2]
```diff
@@ -885,21 +893,28 @@ void cmdHandler_AddEnhancement(const QString &cmd, MapClientSession &sess)
     QVector<QStringRef> args(cmd.splitRef(' '));
     QString name = args.value(1).toString();
     uint32_t level = args.value(2).toInt();
-
-    QString floating_msg = FloatingInfoMsg.find(FloatingMsg_FoundEnhancement).value();
-    QString msg = "Awarding Enhancement '" + name + "' to " + sess.m_ent->name();
+    QString msg = "There was an error adding this enhancement!";
```
Comment (dracc) [inline Projects/CoX/Servers/MapServer/SlashCommand.cpp]: Same here as above

File: Projects/CoX/Servers/MapServer/SlashCommand.cpp (hunk 1 above)
Comment (broxen) [reply Projects/CoX/Servers/MapServer/SlashCommand.cpp]: Thanks for reviewing!

You're completely right. I can simplify this section
