### PR TITLE
Automatic dependency transfer, README edits, and EMOTES!

### LINKED ISSUE #201: Dll's required for utilities are not automatically created/moved upon build
### Expected behavior
Have the several dll's needed for the server utilities to run be automatically created or moved to the "out" folder upon project build.
### Required DLL's
Qt\\[version]\mingw53_32\bin
libgcc_s_dw2-1.dll
libstdc++-6.dll
libwinpthread-1.dll
Qt5Core.dll
Qt5Gui.dll
Qt5Network.dll
Qt5Sql.dll
Qt5Widgets.dll

[Your SEGS build directory]\3rd_party\built\lib
libACE.dll
### Actual behavior/symptoms
They aren't.
### Steps to reproduce behavior/symptoms
1. Build the project.
2. Navigate to the "out" folder of your SEGS directory.
3. Attempting to open any of the utilities will throw a dll error.
### SEGS version
My local copy
### Operating system
Windows 7 64-bit
### C++ compiler and version
Qt Version 5.10.0

### LINKED ISSUE #202: Documentation doesn't specify client command line arguments
Client must be run with ` -project SEGS` command line argument, otherwise it will output error message about patching using coh_updater.exe.

Docs should be updated to reflect this necessary step.

### LINKED ISSUE #203: Tasks for streamlining the initial installation process for newcomers
Many things in the readmes concerning the installation and configuration of the SEGS server and CoX client are either outdated or poorly explained. We should fix these problems so that newcomers can easily join the project.

### Segs/Projects/CoX/docs/README.md
- [x] Under Installation, steps 1 and 2 should be consolidated into 1a and 1b, to clarify that the user should do either one or the other.
- [x] OUTDATED: When the user builds the project, the `/data/` directory is not created by default, so the user will need to do it manually.
- [x] The dll's required for the utilities (like piggtool and authserver) to run are not created or moved to the out folder by default. References Issue #201. EDIT: This now only applies to `libACE.dll`.
- [x] Add more detailed instructions about how to operate piggtool. The user will need to open Windows Command Prompt, navigate to the out folder, and input this command (which is displayed incorrectly in the readme): `piggtool -x ./data/bin.pigg`. The user will then need to move the created bin folder into the `/data/` directory.
- [x] Include instructions on how to configure the CoX client to run without CohUpdater.exe. The user will need to create a shortcut to CoX.exe, and access its properties. In the Target field, the user will need to add `-project SEGS` to bypass the updater. Optional commands for windowed mode: `-fullscreen 0 -screen 1024 768`

### LINKED ISSUE #205: Copy required 3rd_party shared libraries to output directory during build
Since our users/fresh developers might encounter issues when running their built server for the first time, we should make things easier for them.
ACE dll and any other shared libraries should be copied to ```out``` directory.

### PR DESCRIPTION
**Pull request by erpmario**
Closes #201.
Closes #202.
Closes #203.
Closes #205.

This PR is designed to streamline the installation, building, and running process of SEGS for newcomers. Most things can be seen in the commit list, but I'll hit the high points.

Additions/modifications proposed in this pull request:
- Temporarily comment out the creation of the `Projects/CoX/Clients` subdirectory, to avoid errors related to Nemerle's upcoming client patch.
- Add CMake code for automatic transfer of dependencies to the SEGS output directory.
- Change the SEGS output directory from the source directory to the build directory, to avoid intermingling between different builds.
- Update the readme located at `Projects/CoX/docs/README.md` with new information.
    - Add section detailing Qt Visual Studio Tools and why you should absolutely never use it.
    - Change instructions to reflect the output directory now being located in the build directory rather than source.
    - Add instructions to ensure the user's Qt environment is set to "Debug."
    - Add instructions to bypass the `CohUpdater.exe` requirement for the I0 client.
- Add in logic for I0 emotes in `MapInstance.cpp`. Only outputs debug messages. `/fly` outputs a debug message and toggles the variable `m_is_flying`.
- Change the `Entity` variable `mFly` to `m_is_flying` for clarity.
- Add the `toggleFly()` function to the `Entity` class, which simply toggles the variable `m_is_flying`.

### CODE REVIEW

File: Projects/CoX/Servers/MapServer/MapInstance.cpp [hunk 1]
```diff
@@ -23,6 +23,7 @@
 #include "WorldSimulation.h"
 #include "InternalEvents.h"
 
+#include <stdlib.h>
```
Comment (nemerle) [inline Projects/CoX/Servers/MapServer/MapInstance.cpp]: Please reorder includes to follow the canonical order of includes:
FILE.cpp:
```cpp
#include "FILE.h"

#include "project_header1.h"
#include "project_header2.h"

#include <external_dependency.h>
#include <system_header1.h>
```

File: Projects/CoX/Servers/MapServer/MapInstance.cpp [hunk 2]
```diff
@@ -596,6 +599,528 @@ void MapInstance::on_console_command(ConsoleCommand * ev)
...
+        else if(lowerContents == "snowflakes"
+                || lowerContents == "throwsnowflakes")                          // Snowflakes: Throws snowflakes.
+            if(ent->m_is_flying)                                                // Different versions when flying and on the ground.
+                msg = "Unhandled flying Snowflakes emote";                      // Unlocked by purchasing from the Candy Keeper during the Winter Event.
+            else
+                msg = "Unhandled ground Snowflakes emote";
+    }
+    qDebug() << msg;                                                            // Print out the message to the server console.
+    info = new InfoMessageCmd(InfoType::DEBUG_INFO, msg);                       // Create the message to send to the client.
+    src->addCommandToSendNextUpdate(std::unique_ptr<InfoMessageCmd>(info));     // Print the message to the client.
```
Comment (nemerle) [inline Projects/CoX/Servers/MapServer/MapInstance.cpp]: This function will have to be simplified, probably by using data oriented approach to emote storage/processing, maybe the client data files contain emote definitions ?, needs checking

File: Projects/CoX/Servers/MapServer/MapInstance.cpp (hunk 1 above)
Comment (erpmario) [reply Projects/CoX/Servers/MapServer/MapInstance.cpp]: As in, move stdlib.h under the Qt entries?

Comment (nemerle) [reply Projects/CoX/Servers/MapServer/MapInstance.cpp]: Exactly :)

File: Projects/CoX/Servers/MapServer/MapInstance.cpp (hunk 2 above)
Comment (erpmario) [reply Projects/CoX/Servers/MapServer/MapInstance.cpp]: Yeah, of course. This is just rudimentary logic here, so that we can actually know we're interfacing with the client.
